/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AdminImport } from './routes/admin'
import { Route as LayoutImport } from './routes/_layout'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutBookingImport } from './routes/_layout/booking'
import { Route as LayoutServicesHairCutIndexImport } from './routes/_layout/services/hair-cut/index'
import { Route as LayoutServicesHairCutIdImport } from './routes/_layout/services/hair-cut/$id'

// Create/Update Routes

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutBookingRoute = LayoutBookingImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutServicesHairCutIndexRoute = LayoutServicesHairCutIndexImport.update(
  {
    id: '/services/hair-cut/',
    path: '/services/hair-cut/',
    getParentRoute: () => LayoutRoute,
  } as any,
)

const LayoutServicesHairCutIdRoute = LayoutServicesHairCutIdImport.update({
  id: '/services/hair-cut/$id',
  path: '/services/hair-cut/$id',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/_layout/booking': {
      id: '/_layout/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof LayoutBookingImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminImport
    }
    '/_layout/services/hair-cut/$id': {
      id: '/_layout/services/hair-cut/$id'
      path: '/services/hair-cut/$id'
      fullPath: '/services/hair-cut/$id'
      preLoaderRoute: typeof LayoutServicesHairCutIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/services/hair-cut/': {
      id: '/_layout/services/hair-cut/'
      path: '/services/hair-cut'
      fullPath: '/services/hair-cut'
      preLoaderRoute: typeof LayoutServicesHairCutIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutBookingRoute: typeof LayoutBookingRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutServicesHairCutIdRoute: typeof LayoutServicesHairCutIdRoute
  LayoutServicesHairCutIndexRoute: typeof LayoutServicesHairCutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutBookingRoute: LayoutBookingRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutServicesHairCutIdRoute: LayoutServicesHairCutIdRoute,
  LayoutServicesHairCutIndexRoute: LayoutServicesHairCutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/booking': typeof LayoutBookingRoute
  '/': typeof LayoutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/services/hair-cut/$id': typeof LayoutServicesHairCutIdRoute
  '/services/hair-cut': typeof LayoutServicesHairCutIndexRoute
}

export interface FileRoutesByTo {
  '/booking': typeof LayoutBookingRoute
  '/': typeof LayoutIndexRoute
  '/admin': typeof AdminIndexRoute
  '/services/hair-cut/$id': typeof LayoutServicesHairCutIdRoute
  '/services/hair-cut': typeof LayoutServicesHairCutIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_layout/booking': typeof LayoutBookingRoute
  '/_layout/': typeof LayoutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_layout/services/hair-cut/$id': typeof LayoutServicesHairCutIdRoute
  '/_layout/services/hair-cut/': typeof LayoutServicesHairCutIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/admin'
    | '/booking'
    | '/'
    | '/admin/'
    | '/services/hair-cut/$id'
    | '/services/hair-cut'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/booking'
    | '/'
    | '/admin'
    | '/services/hair-cut/$id'
    | '/services/hair-cut'
  id:
    | '__root__'
    | '/_layout'
    | '/admin'
    | '/_layout/booking'
    | '/_layout/'
    | '/admin/'
    | '/_layout/services/hair-cut/$id'
    | '/_layout/services/hair-cut/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/admin"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/booking",
        "/_layout/",
        "/_layout/services/hair-cut/$id",
        "/_layout/services/hair-cut/"
      ]
    },
    "/admin": {
      "filePath": "admin.tsx",
      "children": [
        "/admin/"
      ]
    },
    "/_layout/booking": {
      "filePath": "_layout/booking.tsx",
      "parent": "/_layout"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/admin/": {
      "filePath": "admin/index.tsx",
      "parent": "/admin"
    },
    "/_layout/services/hair-cut/$id": {
      "filePath": "_layout/services/hair-cut/$id.tsx",
      "parent": "/_layout"
    },
    "/_layout/services/hair-cut/": {
      "filePath": "_layout/services/hair-cut/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
